- name: Install RabbitMQ
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure rabbitmq yum repos
    ansible.builtin.shell: "{{item}}"
    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: install the rabittmq
    ansible.builtin.yum:
      name: rabbitmq-server
      state: present

  - name: Start service rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes

  - name: create rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: Set up permissions in RabbitMQ
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
