- name: Install redis component
  hosts: redis
  become: yes
  tasks:
  - name: Installing the redis repo
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
      disable_gpg_check: true

  - name: Enable redis 6.2
    ansible.builtin.yum:
      name: redis:remi-6.2
      state: present
    
  - name: Install redis
    ansible.builtin.yum:
      name: redis
      state: installed


  