- name: Install redis component
  hosts: redis
  become: yes
  tasks:
  - name: Installing the remi release
    ansible.builtin.dnf:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true

  - name: Enable redis
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y
    
  - name: Install redis
    ansible.builtin.dnf:
      name: redis
      state: installed


  