- name: Install user component
  hosts: user
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install NodeJS
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out #output is variable name
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: directory

  - when: directory.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the user artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app 
      remote_src: yes

  - name: install dependences
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy catalouge service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deman reloaded
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing the mongodb-org-shell
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: load user data
    ansible.builtin.shell: mongo --host mongodb.gspaws.online < /app/schema/user.js

  - name: Start service user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes